### PR TITLE
squid:S00118 - Abstract class names should comply with a naming conve…

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar rule squid:S00118 - Abstract class names should comply with a naming convention
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S00118
Please let me know if you have any questions.
M-Ezzat

### CODE REVIEW

**Comment by caarlos0** [comment]
@m-ezzat there is conflicts...

**Comment by m-ezzat** [comment]
@caarlos0 it's fixed, but let me first to squash the commits.

**Comment by caarlos0** [comment]
@m-ezzat thanks

**Comment by m-ezzat** [comment]
you're welcome :)

**Pull request merged**
